gcloud:
  projectID: bq-iot-example-project
  region: europe-west1
  mqtt: tcp://mqtt.googleapis.com:8883
device:
  publicCredentialsPath: ../ec_public.pem
  privateCredentialsPath: ../ec_private.pem
  jwtExpirationInMin: 60
